rails_experiment/game_centre/config/routes.rb
Rails.application.routes.draw do
  root "games#index"
  get '/secret_numbers', to: 'secret_numbers#new'
  resources :secret_numbers, :only => [:new, :show]

end

rails_experiment/game_centre/app/controllers/games_controller.rb
class GamesController < ApplicationController

	def index
	end

end

rails_experiment/game_centre/app/controllers/secret_numbers_controller.rb
class SecretNumbersController < ApplicationController
	def new
	end

	def show
		@secret_number = rand(5)+1
		@chosen_number = params[:id].to_i
	end
end

rails_experiment/game_centre/app/views/games/index.html.erb
<h1>Welcome to the Game Centre!</h1>

<p>Choose a game below to get started:</p>

<ul class="games">
	<li>
		<%=link_to image_tag("games/secret-number.jpg"), new_secret_number_path %>
			<h3>Secret Number</h3>
		<%= image_tag("games/rock-paper-scissors.jpg") %>
		<h3>Rock Paper Scissors</h3>
	</li>
</ul>

rails_experiment/game_centre/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameCentre</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

rails_experiment/game_centre/app/views/secret_numbers/new.html.erb
<h1>Welcome to Secret Number!</h1>

<p> To play, guess a number. if you guess the <em>Secret Number</em> you win</p>

<h2> Pick a number:</h2>
	<% (1..5).each do |number| %>
	<%= link_to image_tag("secret_numbers/#{number}.jpeg"), secret_number_path(number) %>
	<% end %>

rails_experiment/game_centre/app/views/secret_numbers/show.html.erb
<% if @secret_number == @chosen_number %>
	<h1> CONGRATS! You Won! </h1>
	<h3> The scret number was <%= @secret_number%></h3>
	<p> <%= image_tag 'games/cat-wins.gif'%>

<% else %>
	<h1> Sorry you lose ... </h1>
	<h3>The secret number was <%= @secret_number %></h3>
	<p><%= image_tag 'games/loser.gif' %>
<% end %>

<p>
	<%= link_to "PLAY AGAIN!", new_secret_number_path %>
</p>